### Register user
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "login": "user3",
  "password": "content"
}

<> 2025-06-03T181107.500.json
<> 2025-06-03T180623.500.json
<> 2025-06-03T180607.500.json
<> 2025-06-03T180551.500.json

### Login user
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "user3",
  "password": "content"
}

### Получение списка заказов
GET http://localhost:8080/api/user/orders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDkzMjA0MzUsImlhdCI6MTc0OTIzNDAzNSwic3ViIjo3fQ.WRU7NJHSPt1Y7GvsGLfqxw40MWkzOcMqF-FiIPqi-9I


### Загрузка номера заказа
POST http://localhost:8080/api/user/orders HTTP/1.1
Content-Type: text/plain
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk0NjAxMjUsImlhdCI6MTc0OTM3MzcyNSwic3ViIjoxfQ.9tV5qJfI6qLKRot4BNLV7ptRdvefOmd-hhNkic4XTEs

55563340

### Баланс
GET http://localhost:8080/api/user/balance HTTP/1.1
Content-Length: 0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk0NjAxMjUsImlhdCI6MTc0OTM3MzcyNSwic3ViIjoxfQ.9tV5qJfI6qLKRot4BNLV7ptRdvefOmd-hhNkic4XTEs

### Совершенные покупки
GET http://localhost:8080/api/user/withdrawals HTTP/1.1
Content-Length: 0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk0NjAxMjUsImlhdCI6MTc0OTM3MzcyNSwic3ViIjoxfQ.9tV5qJfI6qLKRot4BNLV7ptRdvefOmd-hhNkic4XTEs

### Списание балов
POST http://localhost:8080/api/user/balance/withdraw HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk0NjAxMjUsImlhdCI6MTc0OTM3MzcyNSwic3ViIjoxfQ.9tV5qJfI6qLKRot4BNLV7ptRdvefOmd-hhNkic4XTEs

{
  "order": "2377225624",
  "sum": 750
}


### Добавление заказа в систему начисления балов
POST http://localhost:8081/api/orders HTTP/1.1
Content-Type: application/json

{
  "order": "6545743",
  "goods": [
    {
      "description": "Чайник1 Bork",
      "price": 90000
    },
    {
      "description": "Мешалка Bork",
      "price": 1000
    }
  ]
}

### Получение информации о начислении баллов
GET http://localhost:8081/api/orders/6545743
#GET http://localhost:8081/api/orders/55563340
#GET http://localhost:8081/api/orders/24536757
Content-Length: 0


### Добавление нового бала лояьлности
POST http://localhost:8081/api/goods HTTP/1.1
Content-Type: application/json

{
  "match": "Bork",
  "reward": 10,
  "reward_type": "%"
}

<> 2025-06-03T165832.404.txt
<> 2025-06-03T151042.401.json
<> 2025-06-03T151020.401.json
<> 2025-06-03T150921.409.json
<> 2025-06-03T145844.409.json